spring.config.import=optional:configserver:http://localhost:8888
spring.mongodb.uri=${ACTIVITY_MONGODB_URI}


server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.kafka.bootstrap-servers=localhost:9092


# =========================
# Producer Configuration
# =========================
kafka.topic.name=activity-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer