
spring.mongodb.uri=${ACTIVITY_MONGODB_URI}

server.port=8082

eureka.client.service-url.defaultZone=https://fitness-eureka-oslx.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.kafka.bootstrap-servers=fitness-kafka-fitness-microservices.j.aivencloud.com:17112

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

# =========================
# Producer Configuration
# =========================
kafka.topic.name=activity-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer