server.port=8081

# MySQL Database Configuration
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/fitness_microservice}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

KEYCLOAK_SERVER_URL=http://localhost:8080
KEYCLOAK_REALM=fitness-application
KEYCLOAK_CLIENT_ID=fitness-user-service
KEYCLOAK_CLIENT_SECRET=eayTeZlDV7Ocv87grkK6AkoxPjY6kaTGv7q3IwtzY8dg5o1A4jgygm6hp117DiDVJekkVJq8Og2psfYbcKmFaQ